<a href="https://colab.research.google.com/github/martinbedia/mineria/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduccion

In [ ]:
import numpy as np

Proporciona objetos de tipo ndarray. Son lista eficientes. Tienen tamaño estático. Los elementos son del mismo tipo (mas o menos, podemos crear arrays de tipo distinto).
Tienen funcionalidades precompiladas que son mucho mas eficientes y rapidas
Vectorización y broadcasting

In [ ]:
arr = np.array([3,5,1,7])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


Los arrays son de dimensiones diferentes y la funcion array lo infiere en el momento de la creacion. Pueden tener todas las dimensiones que queremos:
- 0D: es un elemento simple
-1D: es una lista
-2D: es una matriz
-3D: es conjunto de matrices

In [ ]:
arr0D = np.array(34)
print(arr0D)
print(type(arr0D))

34
<class 'numpy.ndarray'>


In [ ]:
arr1D = np.array([3,5,1,7])    #ojo poner los corchetes, lo que recibe la funcion es un objeto de tipo list
print(arr1D)

[3 5 1 7]


In [ ]:
arr2D= np.array([[10,20],[30,40]])
print(arr2D)

arr3D= np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr3D)

[[10 20]
 [30 40]]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


Llamamos dimension a un nivel de profundidad

In [ ]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)

0
1
2


-Funcion: accedemos a ella usamos np.cosa()

-Método: accedemos a ellos a traves de un objeto tipo ndarray, es decir, arr.cosa()

-Propiedades o atributos: accedemos a ellos a traves de un objeto de tipo ndarray pero solo almacenan informacion y no ejecutan funcionalidades arr.cosa ,sin los parentesis

In [ ]:
arr = np.array([3,5,1,2], ndmin=2)
print(arr)
print(arr.ndim)

[[3 5 1 2]]
2


In [ ]:
arr = np.array([[[3,5],[1,2]],[[3,5],[1,2]]], ndmin=2)
print(arr)
print(arr.ndim)

[[[3 5]
  [1 2]]

 [[3 5]
  [1 2]]]
3


# Acceso a los elementos del array


In [ ]:
numeros = np. array([40,10,20,50,60])
print(numeros[0])
print(numeros[-1])

40
60


In [ ]:
print(numeros)
numeros[1]=100
print(numeros)

[40 10 20 50 60]
[ 40 100  20  50  60]


In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print(matriz[0,1])   #para acceder a un elemento de la matriz [fila,columna]

[[1 2 3]
 [4 5 6]]
2


In [ ]:
print(matriz[0,-1])

3


In [ ]:
lista_matrices = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]])
print(lista_matrices)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


In [ ]:
print(lista_matrices[-1,1,0])

400


Al definir un array 3D tenemos 3 ejes:
- El mas externo es el eje de la fila, es decir, cada una de las matrices
- El siguiente es, dentro de una matriz, cada una de las filas
- El siguiente es, para una fila de una matriz, cada una de las columnas

## Slicing

In [ ]:
numeros= [40,100,20,50,60,80,22,34,55]
print(numeros)
numeros[1:3]       #[1,3)
print(numeros[1:6:2])  #inicio:fin:paso
print(numeros[:4])   #desde el principio hasta (con el hasto no incluido)
print(numeros[4:])   #desde el indice (incluido) hasta el final

[40, 100, 20, 50, 60, 80, 22, 34, 55]
[100, 50, 80]
[40, 100, 20, 50]
[60, 80, 22, 34, 55]


In [ ]:
print(numeros[:6:2])
print(numeros[3::2])
print(numeros[::3])    #del inicio al final cada 3

[40, 20, 60]
[50, 80, 34]
[40, 50, 22]


In [ ]:
print(numeros[-3:-1])

[22, 34]


In [ ]:
matriz = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(matriz[1,1:4])    #del segundo fila coge la 2º,3º y 4º columna
print(matriz[0:2,0])
print(matriz[0:2,3:5])


[7 8 9]
[1 6]
[[ 4  5]
 [ 9 10]]


# Tipos de datos
Para consultar cual es tipo de cada uno de los elementos de los arrays utilizamos dtype

In [ ]:
arr = np.array(["perro","gato","ratón"])
print(arr)
print(arr.dtype)

['perro' 'gato' 'ratón']
<U5


In [ ]:
arr = np.array([1,3,5,6],dtype='i4')
print(arr.dtype)


int32


In [ ]:
arr = np.array([1,3,5,6,7,2.3])
print(arr.dtype)
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

float64
[1 3 5 6 7 2]
int32


# Shape (forma)

In [ ]:
arr = np.array([1,3,5,6,7,2.3])
arr.reshape(3,2)

array([[1. , 3. ],
       [5. , 6. ],
       [7. , 2.3]])

# Otras formas de crear arrays

In [ ]:
resultados = np.zeros(4, dtype='i')
print(resultados)

print(np.ones((10,2)))  #tupla, diez filas y dos columnas. sin el 2 y el parentesis hace 10 unos
print(np.arange(8))   #numeros de seguido
print(np.empty(3))

[0 0 0 0]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7]
[1. 1. 1.]


In [ ]:
print("matriz inicial")
arr = np.ones((5,2))
print(arr)
print("despues de modificar un valor")
arr[1,1] = 3
print(arr)
print("matriz aplanada")
print(arr.reshape(-1))  #devuelve un objeto
print("matriz principal")
print(arr)

matriz inicial
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
despues de modificar un valor
[[1. 1.]
 [1. 3.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
matriz aplanada
[1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
matriz principal
[[1. 1.]
 [1. 3.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
matriz_aplanada = arr.reshape(-1)
print(matriz_aplanada)

[1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]


# Filter

In [ ]:
arr= np.array([51,52,53])
print(arr)
x = [True,True,False]
print(arr[x])

[51 52 53]
[51 52]


In [ ]:
arr >= 52

array([False,  True,  True])

In [ ]:
x = arr <=52
print(arr[x])

[51 52]


In [ ]:
lista = [51,52,53]
print(type(lista))

# lista <= 52 esto no funciona

for i in lista:
  print(i<=52)

<class 'list'>
True
True
False


In [ ]:
a = np.array([1,2,3])
b = np.ones(3)
print(a)
print(b)
a+b

[1 2 3]
[1. 1. 1.]


array([2., 3., 4.])

In [ ]:
variado = np.array([True,5,"hola"])
print(variado.dtype)

<U21


# Clase 2

In [1]:
import numpy as np

# Iteraciones

- nditer()
- ndenumerate()

In [3]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [5]:
for i in arr:
  print(i)

1
3
5
7
9


In [6]:
arr = np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
for i in arr:    #recorre el eje mas externo
  print(i)      # imprime cada elemento del eje mas externo (filas)

[0 1 2 3 4]
[5 6 7 8 9]


In [8]:
for fila in arr:
  for col in arr:
    print(fila,col)

[0 1 2 3 4] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8 9]
[5 6 7 8 9] [0 1 2 3 4]
[5 6 7 8 9] [5 6 7 8 9]


In [9]:
for fila in arr:
  for col in fila:
    print(fila,col)

[0 1 2 3 4] 0
[0 1 2 3 4] 1
[0 1 2 3 4] 2
[0 1 2 3 4] 3
[0 1 2 3 4] 4
[5 6 7 8 9] 5
[5 6 7 8 9] 6
[5 6 7 8 9] 7
[5 6 7 8 9] 8
[5 6 7 8 9] 9


In [10]:
arr = np.arange(12).reshape((3,2,2))   #lista de 3 elementos donde cada elemento es una matriz de 2 por 2
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [12]:
for x in np.nditer(arr):
  print(x)  #muestra el valor elemento a elemento en todos los ejes

0
1
2
3
4
5
6
7
8
9
10
11


In [19]:
arr = np.array([1,7,0,8,9,2,3])
mayor_que_5 = np.zeros_like(arr)   #va a contener un 1 si es elemento es mayor que 5
mayor_que_5

#como hacerlo a mano
indice = 0
for x in np.nditer(arr):
  if x > 5:
    mayor_que_5[indice] = 1
  indice += 1
    #actualizar mayor que 5
print(mayor_que_5)

[0 1 0 1 1 0 0]


In [20]:
mayor_que_5 = np.zeros_like(arr)
mayor_que_5

for idx, x in np.ndenumerate(arr):
  if x > 5:
    mayor_que_5[idx] = 1
print(arr)
print(mayor_que_5)

[1 7 0 8 9 2 3]
[0 1 0 1 1 0 0]


#Funciones matemáticas

In [21]:
arr = np.array([4,7,2,5,9,7,8,1])
arr > 5  #todos los operadores logicos estan vectorizados
#hacen las operaciones elemento a elemento (element-wise)

array([False,  True, False, False,  True,  True,  True, False])

In [22]:
a = np.array([3,6,4,8,1,0])
b = np.array([1,2,3,1,2,3])
a + b

array([4, 8, 7, 9, 3, 3])

In [24]:
np.sum(a)   #como si hicieramos un bucle for con un sumatorio

22

In [31]:
print(np.min(a))
print(np.min(b))
print(np.argmin(a))
el_minimo = np.min(b)
b == el_minimo


0
1
5


array([ True, False, False,  True, False, False])

Funciones matemáticas
https://numpy.org/doc/stable/reference/routines.math.html

# Broadcasting
https://numpy.org/doc/stable/user/basics.broadcasting.html

In [32]:
np.arange(4) + 10   #funciona porque hago broadcasting

array([10, 11, 12, 13])

In [ ]:
np.arange(4) + np.arange(3)   # no funciona porque son de longitud diferente

# Copias y vistas

In [33]:
x = np.arange(10)