<a href="https://colab.research.google.com/github/martinbedia/mineria/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduccion

In [1]:
import numpy as np

Proporciona objetos de tipo ndarray. Son lista eficientes. Tienen tamaño estático. Los elementos son del mismo tipo (mas o menos, podemos crear arrays de tipo distinto).
Tienen funcionalidades precompiladas que son mucho mas eficientes y rapidas
Vectorización y broadcasting

In [2]:
arr = np.array([3,5,1,7])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


Los arrays son de dimensiones diferentes y la funcion array lo infiere en el momento de la creacion. Pueden tener todas las dimensiones que queremos:
- 0D: es un elemento simple
-1D: es una lista
-2D: es una matriz
-3D: es conjunto de matrices

In [4]:
arr0D = np.array(34)
print(arr0D)
print(type(arr0D))

34
<class 'numpy.ndarray'>


In [5]:
arr1D = np.array([3,5,1,7])    #ojo poner los corchetes, lo que recibe la funcion es un objeto de tipo list
print(arr1D)

[3 5 1 7]


In [7]:
arr2D= np.array([[10,20],[30,40]])
print(arr2D)

arr3D= np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr3D)

[[10 20]
 [30 40]]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


Llamamos dimension a un nivel de profundidad

In [9]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)

0
1
2


-Funcion: accedemos a ella usamos np.cosa()

-Método: accedemos a ellos a traves de un objeto tipo ndarray, es decir, arr.cosa()

-Propiedades o atributos: accedemos a ellos a traves de un objeto de tipo ndarray pero solo almacenan informacion y no ejecutan funcionalidades arr.cosa ,sin los parentesis

In [13]:
arr = np.array([3,5,1,2], ndmin=2)
print(arr)
print(arr.ndim)

[[3 5 1 2]]
2


In [23]:
arr = np.array([[[3,5],[1,2]],[[3,5],[1,2]]], ndmin=2)
print(arr)
print(arr.ndim)

[[[3 5]
  [1 2]]

 [[3 5]
  [1 2]]]
3


# Acceso a los elementos del array


In [14]:
numeros = np. array([40,10,20,50,60])
print(numeros[0])
print(numeros[-1])

40
60


In [18]:
print(numeros)
numeros[1]=100
print(numeros)

[40 10 20 50 60]
[ 40 100  20  50  60]


In [21]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print(matriz[0,1])   #para acceder a un elemento de la matriz [fila,columna]

[[1 2 3]
 [4 5 6]]
2


In [22]:
print(matriz[0,-1])

3


In [26]:
lista_matrices = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]])
print(lista_matrices)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


In [27]:
print(lista_matrices[-1,1,0])

400


Al definir un array 3D tenemos 3 ejes:
- El mas externo es el eje de la fila, es decir, cada una de las matrices
- El siguiente es, dentro de una matriz, cada una de las filas
- El siguiente es, para una fila de una matriz, cada una de las columnas

# Slicing

In [32]:
numeros= [40,100,20,50,60,80,22,34,55]
print(numeros)
numeros[1:3]       #[1,3)
print(numeros[1:6:2])  #inicio:fin:paso
print(numeros[:4])   #desde el principio hasta (con el hasto no incluido)
print(numeros[4:])   #desde el indice (incluido) hasta el final

[40, 100, 20, 50, 60, 80, 22, 34, 55]
[100, 50, 80]
[40, 100, 20, 50]
[60, 80, 22, 34, 55]


In [35]:
print(numeros[:6:2])
print(numeros[3::2])
print(numeros[::3])    #del inicio al final cada 3

[40, 20, 60]
[50, 80, 34]
[40, 50, 22]


In [36]:
print(numeros[-3:-1])

[22, 34]


In [37]:
matriz = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
print(matriz[1,1:4])    #del segundo fila coge la 2º,3º y 4º columna
print(matriz[0:2,0])
print(matriz[0:2,3:5])


[7 8 9]
[1 6]
[[ 4  5]
 [ 9 10]]


# Tipos de datos
Para consultar cual es tipo de cada uno de los elementos de los arrays utilizamos dtype

In [41]:
arr = np.array(["perro","gato","ratón"])
print(arr)
print(arr.dtype)

['perro' 'gato' 'ratón']
<U5
