<a href="https://colab.research.google.com/github/martinbedia/mineria/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduccion

In [1]:
import numpy as np

Proporciona objetos de tipo ndarray. Son lista eficientes. Tienen tamaño estático. Los elementos son del mismo tipo (mas o menos, podemos crear arrays de tipo distinto).
Tienen funcionalidades precompiladas que son mucho mas eficientes y rapidas
Vectorización y broadcasting

In [2]:
arr = np.array([3,5,1,7])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


Los arrays son de dimensiones diferentes y la funcion array lo infiere en el momento de la creacion. Pueden tener todas las dimensiones que queremos:
- 0D: es un elemento simple
-1D: es una lista
-2D: es una matriz
-3D: es

In [4]:
arr0D = np.array(34)
print(arr0D)
print(type(arr0D))

34
<class 'numpy.ndarray'>


In [5]:
arr1D = np.array([3,5,1,7])    #ojo poner los corchetes, lo que recibe la funcion es un objeto de tipo list
print(arr1D)

[3 5 1 7]


In [7]:
arr2D= np.array([[10,20],[30,40]])
print(arr2D)

arr3D= np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr3D)

[[10 20]
 [30 40]]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


Llamamos dimension a un nivel de profundidad

In [9]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)

0
1
2


funcion: accedemos a ella usamos np.cosa()
metodo: accedemos a ellos a traves de un objeto tipo ndarray, es decir, arr.cosa()
propiedades o atributos: accedemos a ellos a traves de un objeto de tipo ndarray pero solo almacenan informacion y no ejecutan funcionalidades arr.cosa ,sin los parentesis

In [ ]:
arr = np.array([])