<a href="https://colab.research.google.com/github/martinbedia/mineria/blob/main/oct5_ejercicios-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Ejercicios NumPy I

1. Almacena en la variable `arr` un array con 10 ceros, 10 unos y 10 cuatros. Luego imprime el array y su número de elementos por pantalla.
2. Crea la variable `arr` con los números enteros del 20 al 50 e imprímela por pantalla.
3. Crea la variable `arr` con los números pares del 20 al 50 e imprímela por pantalla.
4. Crea la variable `arr` con los números enteros del 20 al 50 que sean múltiplo de 5 e imprímela por pantalla.
5. Crea la variable `arr` con 10 números aleatorios.
6. Crea e imprime la variable `arr`, que será una matriz de 3x3 cuyos elementos son todos 1.
7. Crea e imprime una variable `arr` que con la dimensión 3x5x4 que contenga números aleatorios.
8. Crea e imprime una variable `arr` que contenga:
```
array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])
```
9. Crea e imprime la varible `arr`, que contendrá una matriz de dimensión 10x10 donde todos sus elementos son 0 a excepción de los bordes, que contendrán un 1.
10. Crea e imprime la variable `arr`, que será una matriz de 5x5 cuyos elementos de la diagonal son los valores del 1 al 5 y el resto 0.
11. Crea e imprime la variable `arr`, que será inicalmente una matriz de 3x1 de todo unos y añádele luego una columna adicional de ceros.

12. Crea e imprime una variable `arr` que contenga:
```
array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [101, 111, 121, 131, 141, 151, 161, 171, 181, 191],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [301, 311, 321, 331, 341, 351, 361, 371, 381, 391],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [501, 511, 521, 531, 541, 551, 561, 571, 581, 591],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [701, 711, 721, 731, 741, 751, 761, 771, 781, 791],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [901, 911, 921, 931, 941, 951, 961, 971, 981, 991]])
```
13. Crea el array:
```
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
 ```
 y muesta para cada elemento el mensaje `El elemento en la fila .. y columna .. es ..`
14. Crea un array con los valores del 0 al 20, ambos incluídos, y cambia el signo de los números del 7 al 12 (ambos incluídos).
15. Escribe un trozo de código que termine imprimiendo uno de los posibles mensajes _No hay ceros/Hay ceros_ en función del valor de la variable `no_hay_ceros`, que será `True` en caso de que en el array almacenado en `arr` no hay ningún cero.
16. Asuminedo que todos los valores del array almacenado en `arr` son numéricos, escribe un trozo de código que imprima _Todos positivos_ en caso de que todos sean mayor que cero y _No todos positivos_ en caso contrario.
17. Escribe un trozo de código que imprima _Aceptado_ si la diferencia entre cada par de elementos de los arrays `x` e `y` es siempre menor o igual que 5 y _Rechazado_ en caso contrario.
18. Escribe un trozo de código que imprima `Falta información` si alguno de los elementos del array `arr` tiene un valor NaN y `Todo correcto` en caso contrario.
19. Imprime el mensaje _El resultado es: ..._ tras multiplicar elemento a elemento los vectores `x` e `y` y hacer la suma de los resultados.
20. Comprueba si los arrays `x` e `y` son iguales elemento a elemento

In [21]:
# Ejercicio 1
# Almacena en la variable arr un array con 10 ceros, 10 unos y 10 cuatros. Luego imprime el array y su número de elementos por pantalla.
arr1 = np.zeros(10)
arr2 = np.ones(10)
arr3 = np.array([4,4,4,4,4,4,4,4,4,4])
arr = np.array([arr1,arr2,arr3])

print(arr)
print(arr.size)
print(len(arr))

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [4 4 4 4 4 4 4 4 4 4]]
30
3


In [31]:
arr = np.array([0]*10+[1]*10+[4]*10)
print(arr)
print(arr.size)   #preferible para saber la longitud
print(len(arr))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 4 4]
30
30


In [9]:
# Ejercicio 2
# Crea la variable arr con los números enteros del 20 al 50 e imprímela por pantalla.
arr = np.arange(20,51)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


In [10]:
# Ejercicio 3
# Crea la variable arr con los números pares del 20 al 50 e imprímela por pantalla.
arr = np.arange(20,51,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [11]:
# Ejercicio 4
# Crea la variable arr con los números enteros del 20 al 50 que sean múltiplo de 5 e imprímela por pantalla
arr = np.arange(20,51,5)
print(arr)

[20 25 30 35 40 45 50]


In [33]:
# Ejercicio 5
# Crea la variable arr con 10 números aleatorios.
arr = np.random.rand(10)
print(arr)

[0.06827964 0.42731448 0.42692445 0.80996587 0.01113736 0.95066195
 0.77201815 0.03704905 0.34490991 0.18412604]


In [35]:
# Ejercicio 6
# Crea e imprime la variable arr, que será una matriz de 3x3 cuyos elementos son todos 1.
arr = np.array([1]*9)
arr = arr.reshape(3,3)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
# Ejercicio 7
# Crea e imprime una variable arr que con la dimensión 3x5x4 que contenga números aleatorios.
arr = np.random.rand(60)
arr = arr.reshape(3,5,4)
print(arr)

# en una linea
# arr = np.random.rand(60).reshape(3,5,4)
# print(arr)

[[[0.69378223 0.2235513  0.06873739 0.32246312]
  [0.23121534 0.98562646 0.8038148  0.15222149]
  [0.35346657 0.57343673 0.46313226 0.74752252]
  [0.94243723 0.93679947 0.26775831 0.76978978]
  [0.56299047 0.73904793 0.18196528 0.90991804]]

 [[0.77182325 0.4772426  0.34174643 0.65182432]
  [0.68230194 0.4730434  0.77531962 0.92639234]
  [0.73115991 0.92807903 0.30751147 0.1478018 ]
  [0.94110148 0.24565945 0.8941631  0.40870332]
  [0.3624481  0.94995871 0.27110698 0.81488027]]

 [[0.40757495 0.61141155 0.55079743 0.32799794]
  [0.28835735 0.05252683 0.85415368 0.51768315]
  [0.26063349 0.29884372 0.38976002 0.66213916]
  [0.90392227 0.04964415 0.20054452 0.46588926]
  [0.15048514 0.64614691 0.81459123 0.4291359 ]]]


In [44]:
# Ejercicio 8
# Crea e imprime una variable arr que contenga:
array = np.arange(0,1000,10).reshape(10,10)
print(array)

[[  0  10  20  30  40  50  60  70  80  90]
 [100 110 120 130 140 150 160 170 180 190]
 [200 210 220 230 240 250 260 270 280 290]
 [300 310 320 330 340 350 360 370 380 390]
 [400 410 420 430 440 450 460 470 480 490]
 [500 510 520 530 540 550 560 570 580 590]
 [600 610 620 630 640 650 660 670 680 690]
 [700 710 720 730 740 750 760 770 780 790]
 [800 810 820 830 840 850 860 870 880 890]
 [900 910 920 930 940 950 960 970 980 990]]


In [52]:
# Ejercicio 9
# Crea e imprime la varible arr, que contendrá una matriz de dimensión 10x10 donde todos sus elementos son 0 a excepción de los bordes, que contendrán un 1.
arr = np.zeros(100).reshape(10,10)
arr[[0,0]] = 1
arr[[9,9]] = 1
arr[0:10,0] = np.ones(10)
arr[0:10,-1] = np.ones(10)
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [55]:
# Ejercicio 10
# Crea e imprime la variable arr, que será una matriz de 5x5 cuyos elementos de la diagonal son los valores del 1 al 5 y el resto 0.
arr = np.diag(np.arange(1,6))
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
